// Mocks generated by Mockito 5.4.6 from annotations
// in app/test/admin_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:app/data/datasources/remote/admin_remote_datasource.dart'
    as _i2;
import 'package:app/data/models/user_model.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AdminRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdminRemoteDatasource extends _i1.Mock
    implements _i2.AdminRemoteDatasource {
  @override
  _i3.Stream<List<_i4.UserModel>> watchStudents() => (super.noSuchMethod(
        Invocation.method(
          #watchStudents,
          [],
        ),
        returnValue: _i3.Stream<List<_i4.UserModel>>.empty(),
        returnValueForMissingStub: _i3.Stream<List<_i4.UserModel>>.empty(),
      ) as _i3.Stream<List<_i4.UserModel>>);

  @override
  _i3.Future<void> updateStudentID(
    String? uid,
    String? name,
    String? newId,
    String? adminUid,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStudentID,
          [
            uid,
            name,
            newId,
            adminUid,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String> getUserName(String? uid) => (super.noSuchMethod(
        Invocation.method(
          #getUserName,
          [uid],
        ),
        returnValue: _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #getUserName,
            [uid],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #getUserName,
            [uid],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<List<_i4.UserModel>> getStudentsByDeptSemester(
    String? dept,
    int? semester,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStudentsByDeptSemester,
          [
            dept,
            semester,
          ],
        ),
        returnValue: _i3.Future<List<_i4.UserModel>>.value(<_i4.UserModel>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.UserModel>>.value(<_i4.UserModel>[]),
      ) as _i3.Future<List<_i4.UserModel>>);

  @override
  _i3.Stream<List<_i4.UserModel>> watchTeachersByKey(String? key) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchTeachersByKey,
          [key],
        ),
        returnValue: _i3.Stream<List<_i4.UserModel>>.empty(),
        returnValueForMissingStub: _i3.Stream<List<_i4.UserModel>>.empty(),
      ) as _i3.Stream<List<_i4.UserModel>>);
}
