import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../widgets/admin/admin_scaffold.dart';
import '../../widgets/common/glass_components.dart';
import '../../../domain/entities/announcement.dart';
import '../../../presentation/providers/announcement_provider.dart';

class AdminSendNotificationScreen extends ConsumerStatefulWidget {
  const AdminSendNotificationScreen({super.key});

  @override
  ConsumerState<AdminSendNotificationScreen> createState() =>
      _AdminSendNotificationScreenState();
}

class _AdminSendNotificationScreenState
    extends ConsumerState<AdminSendNotificationScreen> {
  final _titleController = TextEditingController();
  final _bodyController = TextEditingController();
  bool _isSending = false;
  String _targetGroup = 'الكل'; // 'الكل', 'الطلاب', 'الأساتذة' or specific dept
  final int _targetSemester = 0; // 0 for all

  Future<void> _sendNotification() async {
    if (_titleController.text.isEmpty || _bodyController.text.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('الرجاء تعبئة العنوان والرسالة')),
      );
      return;
    }

    setState(() => _isSending = true);

    try {
      final announcement = Announcement(
        id: '', // Generated by Firestore
        title: _titleController.text.trim(),
        body: _bodyController.text.trim(),
        department: _targetGroup,
        semester: _targetSemester,
        createdAt: DateTime.now(),
      );

      await ref.read(addAnnouncementUseCaseProvider).call(announcement);

      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('تم إرسال الإشعار بنجاح')),
      );
      Navigator.pop(context);
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('خطأ: $e')),
      );
    } finally {
      if (mounted) setState(() => _isSending = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return AdminScaffold(
      title: 'إرسال إشعار عام',
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(20),
        child: Column(
          children: [
            _buildTargetSelector(),
            const SizedBox(height: 20),
            GlassTextField(
              controller: _titleController,
              hint: 'عنوان الإشعار',
              icon: Icons.title,
            ),
            const SizedBox(height: 15),
            GlassTextField(
              controller: _bodyController,
              hint: 'نص الرسالة',
              icon: Icons.message,
              maxLines: 4,
            ),
            const SizedBox(height: 30),
            SizedBox(
              width: double.infinity,
              child: ElevatedButton.icon(
                onPressed: _isSending ? null : _sendNotification,
                icon: _isSending
                    ? const SizedBox(
                        width: 20,
                        height: 20,
                        child: CircularProgressIndicator(
                            color: Colors.white, strokeWidth: 2))
                    : const Icon(Icons.send),
                label: Text(_isSending ? 'جاري الإرسال...' : 'إرسال الآن'),
                style: ElevatedButton.styleFrom(
                  backgroundColor: Colors.redAccent,
                  padding: const EdgeInsets.symmetric(vertical: 15),
                  shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(15)),
                ),
              ),
            ),
            const SizedBox(height: 20),
            const Text(
              'ملاحظة: هذا الإجراء سيقوم بإرسال تنبيه لجميع المستخدمين في الفئة المختارة.',
              style: TextStyle(color: Colors.white54, fontSize: 12),
              textAlign: TextAlign.center,
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildTargetSelector() {
    return Container(
      padding: const EdgeInsets.all(5),
      decoration: BoxDecoration(
        color: Colors.white.withValues(alpha: 0.1),
        borderRadius: BorderRadius.circular(15),
      ),
      child: Row(
        children: [
          _targetOption('الكل', 'الكل'),
          _targetOption('Computer Science', 'Computer Science'),
          _targetOption('Mechanical Eng', 'Mechanical Engineering'),
        ],
      ),
    );
  }

  Widget _targetOption(String label, String value) {
    final isSelected = _targetGroup == value;
    return Expanded(
      child: GestureDetector(
        onTap: () => setState(() => _targetGroup = value),
        child: Container(
          padding: const EdgeInsets.symmetric(vertical: 10),
          decoration: BoxDecoration(
            color: isSelected ? Colors.blueAccent : Colors.transparent,
            borderRadius: BorderRadius.circular(12),
          ),
          alignment: Alignment.center,
          child: Text(
            label,
            style: TextStyle(
              fontSize: 12,
              color: isSelected ? Colors.white : Colors.white60,
              fontWeight: FontWeight.bold,
            ),
            textAlign: TextAlign.center,
            maxLines: 2,
          ),
        ),
      ),
    );
  }
}
